### ISSUE TITLE
bno055 not detected via i2c

### ISSUE THREAD

**Issue by RidahHBR** [arduino-libraries/BNO055#2]
Hi, 

I am connecting bno055 shuttle board ( with application board) with Arduino via i2c  but running the program (read_all_data or raw_data) which is provided by Arduino gives problem detecting message  ("Ooops, no BNO055 detected ... Check your wiring or I2C ADDR!").

Also when i run i2c scanner program I see an address of  (0x47)  71 which  should be 0x28 or 0x29 if I'm right. How can i solve this?

Thank you.

**Comment by per1234** [comment]
>when i run i2c scanner program I see an address of (0x47) 71 which should be 0x28 or 0x29 if I'm right.

That's right. This shows that the library is working correctly and the problem is in your hardware. Thus, there is nothing that can be done about your problem here.

This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to provide all the information people will need to help you.

---
EDIT:
RidahHBR's forum thread: https://forum.arduino.cc/index.php?topic=622602

**Comment by RidahHBR** [comment]
Thank you for the help per1234.
